# Generated by Django 3.0.5 on 2020-04-22 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiaoVien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_gv', models.CharField(max_length=10, unique=True, verbose_name='Mã giáo viên')),
                ('ho_ten', models.CharField(max_length=30, verbose_name='Họ tên')),
                ('ngaysinh', models.CharField(max_length=20, verbose_name='Ngày sinh')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Địa chỉ')),
                ('tot_nghiep_tai', models.CharField(blank=True, max_length=30, null=True, verbose_name='Tốt nghiệp tại')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HeDT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenhe', models.CharField(max_length=10)),
                ('key', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HocKi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_hk', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Khoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenkhoa', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_lop', models.CharField(max_length=10, unique=True, verbose_name='Mã lớp')),
                ('si_so_max', models.IntegerField(verbose_name='Sĩ số tối đa')),
                ('created', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('ghi_chu', models.CharField(choices=[('HOCLAI', 'Học lại'), ('LOPMOI', 'Lớp mới')], max_length=20, verbose_name='Ghi chú')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('giang_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.GiaoVien', verbose_name='Giảng viên')),
                ('he_dt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HeDT', verbose_name='Hệ đào tạo')),
            ],
        ),
        migrations.CreateModel(
            name='Nganh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tennganh', models.CharField(max_length=30, unique=True)),
                ('key_nganh', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('khoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Khoa')),
            ],
        ),
        migrations.CreateModel(
            name='NienKhoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nienkhoa', models.CharField(max_length=20)),
                ('namhoc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ThoiGianHoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thu', models.CharField(max_length=10)),
                ('tiet', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoten', models.CharField(max_length=30, verbose_name='Họ tên')),
                ('ngaysinh', models.CharField(max_length=30, verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=10, verbose_name='Giới tính')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('hocluc', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hedt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.HeDT', verbose_name='Hệ đào tạo')),
                ('lop', models.ManyToManyField(blank=True, null=True, to='app.Lop')),
                ('nganh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Nganh', verbose_name='Ngành')),
                ('nien_khoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.NienKhoa', verbose_name='Niên khóa')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_mon', models.CharField(max_length=10, unique=True)),
                ('tenmon', models.CharField(max_length=30)),
                ('tin_chi', models.IntegerField(blank=True, null=True)),
                ('hocki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HocKi', verbose_name='Chọn học kỳ ')),
                ('nganh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Nganh')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('messages', models.TextField(blank=True, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receive', to='app.SinhVien')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lop',
            name='mon_hoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MonHoc', verbose_name='Môn học'),
        ),
        migrations.AddField(
            model_name='lop',
            name='thoi_gian_hoc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ThoiGianHoc', verbose_name='Thời gian học'),
        ),
        migrations.CreateModel(
            name='HocPhiDaDong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_tien', models.IntegerField(verbose_name='Nhập số tiền cần đóng')),
                ('hoc_ki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HocKi', verbose_name='Chọn học kì')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='HocPhiConNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_tien_con_no', models.IntegerField(verbose_name='Số tiền')),
                ('so_du', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('hoc_ki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HocKi', verbose_name='Chọn học kì')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiemHocLai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem_chuyen_can', models.FloatField(blank=True, null=True)),
                ('diem_kiem_tra', models.FloatField(blank=True, null=True)),
                ('diem_cuoi_ki', models.FloatField(blank=True, null=True)),
                ('mon_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MonHoc')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SinhVien')),
            ],
        ),
        migrations.CreateModel(
            name='Diem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem_chuyen_can', models.FloatField(blank=True, null=True)),
                ('diem_kiem_tra', models.FloatField(blank=True, null=True)),
                ('diem_cuoi_ki', models.FloatField(blank=True, null=True)),
                ('mon_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MonHoc')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SinhVien')),
            ],
        ),
        migrations.CreateModel(
            name='DangKiHocThanhCong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Lop')),
            ],
        ),
    ]
